### PR TITLE
ios: redesigned onboarding

### LINKED ISSUE #2302: upon import valid string auto submit

### LINKED ISSUE #2303: ios create account text box autocorrecting and adding spaces

### LINKED ISSUE #2789: revamp onboarding experience

### PR DESCRIPTION
**Pull request by smailbarkouch**
fixes #2302 
fixes #2303
fixes #2789

# Motivation

Most users who download our app find it through the app store through something like a simple search. These users, and even the ones we introduce to Lockbook, need clarification regarding how accounts work. These new onboarding screens aim to clarify that while guiding them through the account creation process.

# Demonstration

iOS:
<details>
New account:

https://github.com/user-attachments/assets/11d57620-9399-4e3f-b6e5-940d52cb163d

Import account:

https://github.com/user-attachments/assets/fb2c9a88-e6ab-4983-bf2d-a6124f07a5dd
</details>

iPad:
<details>

First onboarding screen:

image

Second onboarding screen:

image

Third onboarding screen:

image

Import account screen:

image

</details>

# Additional Notes

A new onboarding screen for macOS will come in the future, so that is why I did not remove `OnboardingState.swift`. In addition, autocomplete for the account phrase in the import account screen is somewhat ambitious and not worth enough to pursue in this PR.

### CODE REVIEW

**Comment by tvanderstad** [comment]
will this fix https://github.com/lockbook/lockbook/issues/2303 or https://github.com/lockbook/lockbook/issues/2302?

**Comment by smailbarkouch** [comment]
> will this fix #2303 or #2302?

It will fix both @tvanderstad.

**Comment by smailbarkouch** [comment]
@ad-tra feedback
+ make the message on the first onboarding screen align with the sub-heading
+ bring "advanced" to the bottom right corner and make it grayed
+ optimize for ipad (make text bigger, center the account phrase, etc)

**Comment by tvanderstad** [comment]
Screenshot 2024-10-08 at 5 01 36 PM

chatgpt's feedback on phrasing (I stand by everything here)

**Pull request merged**
