### PR TITLE
editor: pretty code blocks & block quotes

### PR DESCRIPTION
**Pull request by tvanderstad**
fixes https://github.com/lockbook/lockbook/issues/2450
fixes https://github.com/lockbook/lockbook/issues/2957
fixes https://github.com/lockbook/lockbook/issues/2958

<details>
Screenshot 2024-10-16 at 9 52 47 PM

Screenshot 2024-10-16 at 9 52 33 PM
</details>

### CODE REVIEW

**Comment by BuriedInTheGround** [comment]
### Block quotes

I like the vertical line, as it distinguishes the block quote content from italic text. My only nit is with the color: I think a shade of gray would be a better choice, as I would reserve colors for [alerts](https://github.com/orgs/community/discussions/16925) from [GitHub Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) (#2732).

### Code blocks

I appreciate the background (I would've asked for it in the near future!).

On a different note, I think the first line of a code block (touching the opening backticks) should be hidden when the cursor (and pointer) is outside, or at least displayed differently, as it usually indicates the "type" of code in the block.

code block example

**Comment by tvanderstad** [comment]
I'm persuaded by your argument for gray block quote lines! Here's a demo of the code block copy button that only shows when hovered. I made the block quote lines gray as well. 

<details>

https://github.com/user-attachments/assets/61a75556-bc45-43b8-985e-8253c16a6813

</details>

The button is smaller than GitHub's button because theirs looks strange when the code block is empty:
```
```

**Comment by tvanderstad** [comment]
> On a different note, I think the first line of a code block (touching the opening backticks) should be hidden when the cursor (and pointer) is outside, or at least displayed differently, as it usually indicates the "type" of code in the block.

When the syntax is hidden we call that 'character capture. It's received some improvements that aren't in the released version yet ([PR with demo](https://github.com/lockbook/lockbook/pull/2902)) but I don't think those address your ask. Since the update, the behavior is that whenever the cursor is in text in some markdown node, whether that's the syntax for the node or the text itself, the syntax for the node isn't captured. Some examples:
* `| **text**`: the syntax is captured because the cursor is outside
* ` |**text**`: the syntax isn't captured because the cursor borders the syntax
* ` **te|xt**`: the syntax isn't captured because the cursor is inside the markdown node

For code blocks the behavior hasn't received any special attention, so similar examples apply:
1. captured:
```
|
'''
text
'''
```
2. not captured:
```

|'''
text
'''
```
3. not captured:
```

'''
te|xt
'''
```

So the behavior is basically defined in terms of what cursor placements capture the syntax or don't. Do you think it'd be better for the syntax to be captured in example 3? How about the following border cases?

4.
```

'''
|text
'''
```
5.
```

'''
text|
'''
```

**Comment by BuriedInTheGround** [comment]
> Do you think it'd be better for the syntax to be captured in example 3?

I don't get your question here. Do you mean like "language tag" instead of "syntax" (e.g. "rust")?

As for the examples 4 and 5, I think they should behave like 2 and 3. Even better, I think that "rust", in the examples here, when captured should either become hidden together with the backticks or become a badge indicating the language (see image to get an idea, even though in that position it would overlap with the copy button).

code snippet

### Example

#### Not captured
``` 
'''rust
te|xt
'''
```
Thus, it looks like (i.e. no change)
``` 
'''rust
te|xt
'''
```

#### Captured (hidden)
``` 
|
'''rust
text
'''
```
Thus, it looks like
``` 
|
text
```

#### Captured (badge)
``` 
|
'''rust
text
'''
```
Thus, it looks (more or less) like
``` 
|
[Rust]
text
```
And, if the language tag is empty, it falls back to look like
``` 
|
text
```

**Comment by tvanderstad** [comment]
> I don't get your question here. Do you mean like "language tag" instead of "syntax" (e.g. "rust")?

I mean both the language tag ("rust") and the syntax (`'''`). When your cursor is in the code block like you're typing the code, would you prefer to see:
1. uncaptured
```
'''rust
text|
'''
```
2. captured, with a badge for the language
```
text|
```

**Comment by BuriedInTheGround** [comment]
Oh, I get it, while typing the code I'd prefer to see the uncaptured version! :)

**Comment by tvanderstad** [comment]
Another note on the layout: at one point we captured the whole first and last line of the syntax (`'''`) for a code block, but we changed our minds about it. The syntax is captured based on where the cursor is but you can also hover the pointer over a markdown node to reveal its syntax. With the whole lines being captured, the text would jump around as you moused over the document and lines were captured/uncaptured. Sometimes capturing a line changed what you were hovering, which caused the line to no longer be captured, and the capture would enter a loop alternating captured and not captured every frame... it was a whole mess haha.

```
''' <- these get captured but the line stays where it is
code
''' <- also captured
```

So it's easier for us to leave the line there even when the syntax is captured. That also leaves space at the top of the code block where we can put the language badge, which I think makes a lot of sense because that's approximately where it is in the source text. When you click on the badge to edit it and the syntax and language are un-captured, you'll be editing the language basically where it just was when it was captured and rendered as a badge.

I'm being a little wordy but here's a summary of what I have in mind:
* When your cursor is in the first or last line of a code block (the lines with `'''rust` or `'''`), we don't capture the text
```
'''rust|
code
'''
```
* When your cursor is in the code in the code block, I haven't decided, I'm open to capturing or not capturing the text (see comment above)
* When your cursor is outside the code block, the syntax and language will be captured but the lines will still be there as part of the code block. If there's a language, it'll be displayed on the top left in a badge. Clicking here will place the cursor on this line, un-capturing the syntax and language based on the behavior in the first bullet
```
[rust badge]
code

```

**Comment by BuriedInTheGround** [comment]
I totally understand the problems you had with removing whole lines, so the current approach of keeping them empty is good and clear in its behavior in my opinion.

I like your direction! To me, when the cursor is in the code inside the code block, the behavior should match the one of other markup elements (e.g. bold multi-line text), with the language tag being considered part of the markup syntax (and thus getting captured along with backticks when they do). This would kind of contrast with my answer from earlier, if we consider the current behavior (it could be fine, though).

**Comment by tvanderstad** [comment]
Great! I'll aim to merge this basically as-is. It'll circulate among the team for feedback and QA and go out in the next release in ~2 weeks. We'll discuss the capture rules for code blocks too and see what feels right

**Pull request merged**
