### PR TITLE
workspace: prettier tab strip

### PR DESCRIPTION
**Pull request by tvanderstad**
fixes https://github.com/lockbook/lockbook/issues/2955

Screenshot 2024-10-16 at 7 33 25 PM
Screenshot 2024-10-16 at 7 34 46 PM

### CODE REVIEW

**Review by ad-tra — APPROVED** [review]
this is sick. THANK YOU, finally getting rid of the old ugly tab strip.
LGTM but my two nits are:
- i think the text can be made smaller to further decrease the height of the toolbar.  this tab strip is thinner than the old one but still thicker than a lot of common apps like vscode and chrome. 
- the closing hover rect is quite ugly, it would be nice to fix it too. it's up to you if you wanna do that or not tbh. image

**Comment by tvanderstad** [comment]
@ad-tra How's this look to you?

Screenshot 2024-10-16 at 10 01 13 PM

**Comment by tvanderstad** [comment]
I made the text smaller but I like the tab strip height because it matches the [toolbar](https://github.com/lockbook/lockbook/pull/2959)

Screenshot 2024-10-16 at 10 04 54 PM

**Comment by Parth** [comment]
nice, I think this is def better than what we have now

the tabs look super wide to me, how does vscode (or any other app you like) handle this? 

There's also something about the colors that give me a bit of "dated" vibes trying to think about what we can do about that

**Comment by tvanderstad** [comment]
VSCode just makes the text smaller. FWIW, the screenshots have the app sized at 1/4 of my screen, so they may look wider than they really are (they're less wide than currently on master)

**Comment by tvanderstad** [comment]
Chrome wraps the text so all the tabs are the same width which is nice if you want to close a bunch of tabs by clicking in the same place over and over

**Comment by Parth** [comment]
uniformly sized tabs seems appealing, we can have some rules for a small amount of tabs

**Comment by smailbarkouch** [comment]
Looks great! My only nit is that the toolbar isn't the same color as the toolbars for the PDF viewer or Canvas. It looks a bit odd.

For instance:
<details>

image
</details>

**Comment by BuriedInTheGround** [comment]
Much cleaner, I love it! (The reviewed closing hover rectangle is definitely better with the lighter gray.)

### About horizontal size

I like uniformly sized tabs, with text fading on the left (possibly), like in Chrome or Firefox.

However, I think it's much easier to have many tabs in Lockbook than in a browser, especially if you don't bother closing them, so they may shrink quite fast and become very tiny (and basically indistinguishable since you can't read the titles). For this reason, I think that fixed sized tabs (I suggest around ~25 characters) might be a better option, along with keeping the current scrolling behavior.

Personally, I'd prefer uniformly sized tabs since scrolling horizontally annoys me, but I think that some sort of auto-close rule or something alternative should be implemented to deal with a fast-growing number of open tabs in an automatized manner.

**Comment by smailbarkouch** [comment]
Another note, when you scroll down into a markdown document, the divider under the tab strip partially disappears (except on the left and right ends).

For instance:
<details>

image
</details>

**Comment by tvanderstad** [comment]
> Another note, when you scroll down into a markdown document, the divider under the tab strip partially disappears (except on the left and right ends).

This issue tracked by https://github.com/lockbook/lockbook/issues/2956 and fixed by https://github.com/lockbook/lockbook/pull/2959 👍

**Comment by tvanderstad** [comment]
In this iteration, tabs are a fixed width regardless of how many there are or how long their titles are. The text fills the tab and is truncated with '...'. When the close button is shown, it's truncated a little harder to make space for the button. If you add enough tabs, you still get a scrollbar (I don't love Chrome's behavior where the tabs get smaller and smaller). I do like how Chrome fades the text out instead of using '...' but this is what's built-in to egui so I think this is the effort it deserves for now.

For scale, I took this screenshot with the window at 1/2 width and 1/2 height of my screen. I'm on macOS with the smallest display scaling setting. The tab width here is 160px so there's no issue having 10 of them open if your window is maximized.
<details>
Screenshot 2024-10-17 at 5 24 04 PM
</details>

**Comment by BuriedInTheGround** [comment]
I like the result and I think the sizing looks fine. Also, now that I see it, I don't really mind '...' that much, and I'm not sure that the fading would fit the overall look (tough I also like it on my browser).

Would it be possible to display the full title when hovering a tab? (See the screenshot below, on Firefox. You don't see my pointer, but it's there, my screenshotting tool hides it.)

image

**Comment by tvanderstad** [comment]
> Would it be possible to display the full title when hovering a tab?

🫡 
Screenshot 2024-10-17 at 6 33 14 PM

**Pull request merged**
