### PR TITLE
docs: update apple build guide

### PR DESCRIPTION
**Pull request by CoreyCole**
* added step to run the workspace-ffi create_libs.sh
* added what to open with xcode
* added how to sign the app

### CODE REVIEW

**Review by Parth — APPROVED** [review]
🎉

**Comment by CoreyCole** [comment]
In order to sign the app with my personal apple dev email, I needed to change the Bundle Identifier. This shouldn't cause any weirdness, right? Nothing is expecting an exact id of `app.lockbook`

**Comment by CoreyCole** [comment]
image

changing the bundle id might have borked the subscription from the app store

**Comment by Parth** [comment]
Potentially we could discuss this in an issue that is a little more centered around improving the external apple dev experience.

I would be curious to see what the error message was that prompted you to change the bundle identifier, just curious about it. I wonder if there was another solution to that problem, I believe we could author a run configuration which doesn't require signing to run. I'm not sure what the implications would be for running on physical devices, but I think it would be permissive and probably the best first approach.

Alternatively: I can't think of any other components apart from the billing related stuff that would care about this. Potentially we could author a run configuration in xcode that disables these things either under the condition.

**Pull request merged**
