### PR TITLE
server: allow un-auth'd requests for build info for monitoring purposes

### LINKED ISSUE #271: Page on call if server is offline
Relying on error logs isn't enough. If someone trips over a power chord over at digital ocean, we should be paged. 

Also page if version is incorrect.

### PR DESCRIPTION
**Pull request by Parth**
closes #271

### CODE REVIEW

**Comment by plv** [comment]
What kind of monitoring purposes? Doesn't removing auth requirement here allow for request flooding of some sort?

**Comment by Parth** [comment]
@plv Checkout ea7fc28 to see my motivation, I want to be paged if the server is ever offline. This is roughly the same number of CPU cycles as if someone were to flood any of the other non-matching endpoint, this request is handled entirely from memory without any IO, so attacking this is similar to attacking `/fjkslfjaslkfjsd`.

**Review by tvanderstad — APPROVED** [review]

**Comment by plv** [comment]
SGTM, in the future might be better to provide Github Actions with a secret that it can use to authenticate itself, giving us the best of both worlds.

**Comment by Parth** [comment]
@plv think about this endpoint tho -- evaluating that secret is roughly as much computation as evaluating an env var and returning the answer.

I agree however if we want this health check to talk to pg / s3.

**Pull request merged**
