### PR TITLE
website: Move the main title heading and compress the text.

### PR DESCRIPTION
**Pull request by steverusso**
This PR moves the main title heading to just above the other content and makes each section of text one paragraph instead of multiple. Due to these changes, the `main` element was also given a `max-width`.

It also includes a small syntax fix.

### CODE REVIEW

**Comment by raayan** [comment]
Steve!

**Comment by Parth** [comment]
Looks like this: 

Wire 2020-07-25 at 8_24 PM

**Comment by Parth** [comment]
Looks great, thanks @steverusso!

**Comment by Parth** [comment]
(Only failures are slack notifications) @raayan maybe compute should have these secrets on there

**Pull request merged**
