### PR TITLE
apple: fix rename and create folder dialogs

### LINKED ISSUE #2526: create folder sheet has no create button

### LINKED ISSUE #2574: Excessive white space in "X" box div
The "X" box appears to have excessive white space surrounding it which creates unnecessary visual clutter.

Screenshot 2024-03-06 at 3 41 39 PM

### PR DESCRIPTION
**Pull request by smailbarkouch**
**Create folder**

<details>
Before:
create-folder-before

After:
create-folder-after
</details>

**Rename file**

<details>

Before:
rename-folder-before

After:
rename-file-after
</details>

fixes #2574
fixes #2526

### CODE REVIEW

**Review by Parth — CHANGES_REQUESTED** [review]
not sure what's going on with your diff but it looks like changes to `Cargo.lock` are unintentional

**Comment by smailbarkouch** [comment]
> not sure what's going on with your diff but it looks like changes to `Cargo.lock` are unintentional

When I deleted and remade the `Cargo.lock` in the android PR, it somehow stopped macOS (and only macOS) workspace libs from working. Essentially, XCode can't link the library to the app when I try to run it. Going to figure out specifically what's causing it. Sounds like a new library version triggered this bug.

**Comment by smailbarkouch** [comment]
The changes in the `Cargo.lock` introduced in this PR are just the original `Cargo.lock`. Didn't mean to mark this as completed without fixing the root issue. (but also felt it was out of place for this PR)

**Comment by Parth** [comment]
Okay, happy to help debug cargo issues if you get stuck

**Review by Parth — APPROVED** [review]

**Pull request merged**
